name: Flutter_iOS

on:
  push:
    branches: [main]

jobs:
 build_ios:
   runs-on: macos-latest

   steps:
   - name: Checkout the code
     uses: actions/checkout@v2
     
         jobs:
         deploy_ios:
         runs-on: macos-latest

            steps:
             -name: Run build script
             run:./github/scripts/pubspec copy.yaml
  
